timeout: 3
/AtlasOS64
    protocol: limine
    resolution: highest
    path: boot():/boot/kernel64.sysaxf
    module_path: boot():/boot/sys64/initramfs.axf
    module_path: boot():/boot/sys64/fonts/zap-light16.psf
    module_path: boot():/boot/sys64/fonts/Arabic.psf
    module_path: boot():/boot/sys64/kern64.config
    module_path: boot():/boot/sys64/AtlasOS256.bmp
    module_path: boot():/boot/sys64/wallpaper.bmp
